ambari-server:
  IP: 10.132.0.2
  FQDN:
hosts:
  - IP: 10.132.0.3
    FQDN:
  - IP: 10.132.0.4
    FQDN:
  - IP: 10.132.0.5
    FQDN:
  - IP: 10.132.0.6
    FQDN:
  - IP: 10.132.0.7
    FQDN:
  - IP: 10.132.0.8
    FQDN:
  - IP: 10.132.0.9
    FQDN:
